const fs = require('fs');
const crypto = require('crypto');
const archiver = require('archiver');
const { logError } = require('./error-log');
const { sanitizeFilename } = require('./utils');

function htmlChaptersToEpub(title, author, htmlChapters, filepath, insertTitlePage, callback){
    //htmlChapters should be an array of objects with a title property and an html property
    if(insertTitlePage){
        htmlChapters.unshift({
            title: 'Title Page',
            html: getTitlePageBody(title, author)
        });
    }

    const uuid = crypto.randomUUID();

   // const epubName = sanitizeFilename(title) + '.epub';
    //const output = fs.createWriteStream(saveDir + "/" + epubName);
    //filepath includes name/extension
    const output = fs.createWriteStream(filepath);
    const archive = archiver('zip', {
        zlib: { level: 9 }
    });

     archive.on('warning', function(err) {
      if (err.code === 'ENOENT') {
        logError(err);
      } else {
        throw err;
      }
    });

    archive.on('error', function(err) {
      callback('error');
      throw err;
    });

    //Listen on the write stream's 'close', not archive's 'finish': 'finish' only means archiver
    //has pushed the last bytes into the pipe, not that fs has flushed them to disk. Calling back
    //before that risks handing off a truncated epub (e.g. to the email attachment code).
    output.on('close', function(){
      callback(filepath);
    })

    archive.pipe(output);

    archive.append(getMimetype(), { 
        name: 'mimetype',
        store: true 
    });

    archive.append(getContainerXml(), {name: 'META-INF/container.xml'});

    const contentDir = 'OEBPS/';

    archive.append(getContentOpf(title, author, htmlChapters, uuid), {name: contentDir + 'content.opf'});
    archive.append(getTocNcx(title, htmlChapters, uuid), {name: contentDir + 'toc.ncx'});
    archive.append(getTocXhtml(htmlChapters), {name: contentDir + 'toc.xhtml'});

    var pages = getChapterXhtmlPages(htmlChapters);
    pages.forEach(function(page, i){
        archive.append(page, {name: contentDir + 'chapter_' + (i + 1) + '.xhtml'});
    });

    archive.append(getCss(), {name: contentDir + 'CSS/template.css'});

    archive.finalize();
};

function getMimetype(){
    return 'application/epub+zip';
}

//Metadata fields (title, author, chapter titles) are plain text with no markup of their own,
//so every reserved XML character in them must be escaped or a title/author containing e.g.
//"&", "<" or "\"" breaks the well-formedness of content.opf/toc.ncx/toc.xhtml and epubcheck
//(and many readers) will reject the whole book.
function escapeXmlText(str){
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

//Chapter bodies already contain real markup generated by mdfc-to-html (<p>, <b>, <br/>, etc.),
//so they can't be fully XML-escaped without mangling the tags. But raw "&" typed by the author
//(e.g. "Marks & Spencer") is left untouched by that conversion and is the single most common
//way real prose breaks XHTML well-formedness, so escape any "&" that isn't already the start of
//a valid entity reference.
function escapeBareAmpersands(str){
    return String(str).replace(/&(?!(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/g, '&amp;');
}

function getContainerXml(){
    return '<?xml version="1.0"?>' +
	'<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">' +
	'<rootfiles>' +
	'	<rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>' +
	'</rootfiles>' +
	'</container>';
}

function getContentOpf(title, author, htmlChapters, uuid){
    const now = new Date();
    const isoFormattedDate = now.toISOString();
    const formattedWithoutMilliseconds = isoFormattedDate.slice(0, 19) + 'Z';

    var opf = '<?xml version="1.0" encoding="UTF-8" ?>' +
	'<package xmlns="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" unique-identifier="db-id" version="3.0">' +
	'' +
	'	<metadata>' +
	'	    <dc:title id="t1">' + escapeXmlText(title) + '</dc:title>' +
	'	    <dc:creator id="creator">' + escapeXmlText(author) + '</dc:creator>' +
    '       <dc:identifier id="db-id">' + uuid + '</dc:identifier>' + 
    '       <meta property="dcterms:modified">' + formattedWithoutMilliseconds + '</meta>' + 
	'	    <dc:language>en</dc:language>' +
	'	</metadata>';

    opf += '<manifest>' +
	'	    <item id="toc" properties="nav" href="toc.xhtml" media-type="application/xhtml+xml" />' +
	'	    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml" />' +
	'	    <item id="template_css" href="CSS/template.css" media-type="text/css" />';

    for(let i=1;i<htmlChapters.length + 1;i++){
         opf += '<item id="chapter_' + i + '" href="chapter_' + i + '.xhtml" media-type="application/xhtml+xml" />';
    }

    opf += '</manifest>' +
	'	<spine toc="ncx">' +
	'		<itemref idref="toc" />';

    for(let i=1;i<htmlChapters.length + 1;i++){
        opf += '<itemref idref="chapter_' + i + '" />';
    }

    opf += '</spine>' +
	'</package>';

 return opf;  
}

function getTocNcx(title, htmlChapters, uuid){
    var ncx = '<?xml version="1.0" encoding="UTF-8" ?>' +
	'<ncx version="2005-1" xml:lang="en" xmlns="http://www.daisy.org/z3986/2005/ncx/">' +
	'<head>' +
	'    <meta name="dtb:uid" content="' + uuid + '"/>' +
	'    <meta name="dtb:depth" content="1"/>' +
	'    <meta name="dtb:totalPageCount" content="0"/>' +
	'    <meta name="dtb:maxPageNumber" content="0"/>' +
	'</head>' +
	'<docTitle>' +
	'    <text>' + escapeXmlText(title) + '</text>' +
	'</docTitle>' +
	'<navMap>';

    for(let i=1;i<htmlChapters.length + 1;i++){
        ncx += '<navPoint id="chapter_' + i + '" playOrder="' + i + '">' +
	'		<navLabel><text>' + escapeXmlText(htmlChapters[i - 1].title) + '</text></navLabel>' +
	'		<content src="chapter_' + i + '.xhtml" />' +
	'	</navPoint>';
    }

    ncx += '</navMap>' +
        '</ncx>';

    return ncx;
}

function getTocXhtml(htmlChapters){
    var xhtml = '<?xml version="1.0" encoding="utf-8"?>' +
	'<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">' +
	'<head>' +
	'<title>toc.xhtml</title>' +
	'<link href="CSS/template.css" rel="stylesheet" type="text/css" />' +
	'</head>' +
	'<body>' +
	'    <nav id="toc" epub:type="toc">' +
	'        <h1 class="frontmatter">Table of Contents</h1>' +
	'        <ol class="contents">';

    for(let i=1;i<htmlChapters.length + 1;i++){
        xhtml += '<li><a href="chapter_' + i + '.xhtml">' + escapeXmlText(htmlChapters[i - 1].title) + '</a></li>'
    }

    xhtml += '</ol>' +
	'    </nav>' +
	'</body>' +
	'</html>';

    return xhtml;
}

function getChapterXhtmlPages(htmlChapters){
    var pages = [];

    htmlChapters.forEach(function(chap, i){
        pages.push('<?xml version="1.0" encoding="utf-8"?>' +
        '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">' +
        '<head>' +
        '<title>chapter_' + (i + 1) + '.xhtml</title>' +
        '<link href="CSS/template.css" rel="stylesheet" type="text/css" />' +
        '</head>' +
        '<body>' +
        escapeBareAmpersands(chap.html) +
        '</body>' +
        '</html> ')
    });

    return pages;
}

function getTitlePageBody(title, author){
    return '<h1 class="center title">' + escapeXmlText(title) + '</h1>' +
        '<h2 class="center">by ' + escapeXmlText(author) + '</h2>';
}

function getCss(){
    return ".contents { list-style-type: none; } " + 
        ".title { margin-top: 33% }" + 
      "      h1 {" +
      "        white-space: pre-wrap;" +
      "      }" +
      "    p {" +
      "      white-space: pre-wrap;" +
      "      margin-top: 0px;" +
      "      margin-bottom: 0px;" +
      "    }" +
      "    .center {" +
      "      text-align: center;" +
      "    }" +
      "    .right {" +
      "      text-align: right;" +
      "    }" +
      "    .justified {" +
      "      text-align: justify;" +
      "    } " +
      "    blockquote {" +
      "      white-space: pre-wrap;" +
      "    }" +
      "    .footnote {" +
      "      text-indent: 1em;" +
      "    }" +
      "    .footnote p:nth-child(1n+2) {" +
      "      text-indent: 2em;" +
      "    }" +
      "    sup {" +
      "      margin-right: 0.25em;" +
      "    }";
}

module.exports = {
    htmlChaptersToEpub
}