const fs = require('fs');
const crypto = require('crypto');
const archiver = require('archiver');
const { logError } = require('./error-log');

function htmlChaptersToEpub(title, author, htmlChapters, filepath, insertTitlePage, callback){
    //htmlChapters should be an array of objects with a title property and an html property.
    //Build a new array rather than unshift()-ing in place: callers construct this array fresh
    //today, but mutating an argument the caller still holds a reference to is a footgun waiting
    //for a caller that doesn't.
    if(insertTitlePage){
        htmlChapters = [{
            title: 'Title Page',
            html: getTitlePageBody(title, author)
        }, ...htmlChapters];
    }

    const uuid = crypto.randomUUID();

    //filepath includes name/extension
    const output = fs.createWriteStream(filepath);
    const archive = archiver('zip', {
        zlib: { level: 9 }
    });

    //An output-stream failure (e.g. ENOSPC, EACCES, a missing parent directory) and archiver's
    //own 'error' event can both fire for the same underlying problem, and callers (email-doc.js,
    //compile.js) aren't written to tolerate the completion callback firing more than once.
    var finished = false;
    function finish(result){
      if(finished) return;
      finished = true;
      callback(result);
    }

     archive.on('warning', function(err) {
      //Not fatal - archiver already recovered (e.g. a stat failed on an entry). Rethrowing here
      //would throw from inside an event handler with no surrounding try/catch to catch it,
      //crashing the process instead of just losing this one warning.
      logError(err);
    });

    archive.on('error', function(err) {
      logError(err);
      finish('error');
    });

    //Node throws an uncaught exception on an unhandled 'error' event, so the write stream needs
    //its own listener - without one, a disk-level failure (full disk, permission denied, missing
    //parent directory) crashes the process instead of reaching the callback.
    output.on('error', function(err){
      logError(err);
      finish('error');
    });

    //Listen on the write stream's 'close', not archive's 'finish': 'finish' only means archiver
    //has pushed the last bytes into the pipe, not that fs has flushed them to disk. Calling back
    //before that risks handing off a truncated epub (e.g. to the email attachment code).
    output.on('close', function(){
      finish(filepath);
    })

    archive.pipe(output);

    archive.append(getMimetype(), { 
        name: 'mimetype',
        store: true 
    });

    archive.append(getContainerXml(), {name: 'META-INF/container.xml'});

    const contentDir = 'OEBPS/';

    archive.append(getContentOpf(title, author, htmlChapters, uuid), {name: contentDir + 'content.opf'});
    archive.append(getTocNcx(title, htmlChapters, uuid), {name: contentDir + 'toc.ncx'});
    archive.append(getTocXhtml(htmlChapters), {name: contentDir + 'toc.xhtml'});

    var pages = getChapterXhtmlPages(htmlChapters);
    pages.forEach(function(page, i){
        archive.append(page, {name: contentDir + 'chapter_' + (i + 1) + '.xhtml'});
    });

    archive.append(getCss(), {name: contentDir + 'CSS/template.css'});

    archive.finalize();
};

function getMimetype(){
    return 'application/epub+zip';
}

//Metadata fields (title, author, chapter titles) are plain text with no markup of their own,
//so every reserved XML character in them must be escaped or a title/author containing e.g.
//"&", "<" or "\"" breaks the well-formedness of content.opf/toc.ncx/toc.xhtml and epubcheck
//(and many readers) will reject the whole book.
function escapeXmlText(str){
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

//Chapter bodies already contain real markup generated by mdfc-to-html (<p>, <b>, <br/>, etc.),
//so they can't be fully XML-escaped without mangling the tags. But raw "&" typed by the author
//(e.g. "Marks & Spencer") is left untouched by that conversion and is the single most common
//way real prose breaks XHTML well-formedness, so escape any "&" that isn't already the start of
//a valid entity reference.
function escapeBareAmpersands(str){
    return String(str).replace(/&(?!(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/g, '&amp;');
}

//Chapter bodies contain real markup generated by mdfc-to-html.js (headings, paragraphs, lists,
//bold/italic/underline/strike, footnotes, links) that can't be escaped wholesale without mangling
//it. But a "<" or ">" typed by the author as literal prose - a comparison ("5 < 3"), an emoticon
//("<3"), or a name written as "<Empire>" - is the other common way real prose breaks XHTML
//well-formedness (alongside a bare "&", above). Recognise exactly the tag shapes mdfc-to-html.js
//emits and escape every other "<"/">" as literal text.
const KNOWN_TAG = /<\/?(?:h[1-4](?: class="(?:center|right|center title)")?|p(?: class="(?:left|right|center|justified)")?|li(?: class="(?:ul|ul ul-two|ul ul-three|ol|ol ol-two|ol ol-three)")?|ul|ol|blockquote|b|i|u|del|sup|div(?: class="footnote" id="fnote_\d+")?|a(?: href="#fnote(?:Ref)?_\d+"(?: id="fnoteRef_\d+")?)?)\s*>|<br\s*\/>/g;

function escapeBareAngleBrackets(str){
    str = String(str);

    var result = '';
    var lastIndex = 0;
    var match;

    KNOWN_TAG.lastIndex = 0;
    while((match = KNOWN_TAG.exec(str)) !== null){
        result += escapeAngleBrackets(str.slice(lastIndex, match.index)) + match[0];
        lastIndex = KNOWN_TAG.lastIndex;
    }
    result += escapeAngleBrackets(str.slice(lastIndex));

    return result;
}

function escapeAngleBrackets(str){
    return str.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function getContainerXml(){
    return '<?xml version="1.0"?>' +
	'<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">' +
	'<rootfiles>' +
	'	<rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>' +
	'</rootfiles>' +
	'</container>';
}

function getContentOpf(title, author, htmlChapters, uuid){
    const now = new Date();
    const isoFormattedDate = now.toISOString();
    const formattedWithoutMilliseconds = isoFormattedDate.slice(0, 19) + 'Z';

    var opf = '<?xml version="1.0" encoding="UTF-8" ?>' +
	'<package xmlns="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" unique-identifier="db-id" version="3.0">' +
	'' +
	'	<metadata>' +
	'	    <dc:title id="t1">' + escapeXmlText(title) + '</dc:title>' +
	'	    <dc:creator id="creator">' + escapeXmlText(author) + '</dc:creator>' +
    '       <dc:identifier id="db-id">' + uuid + '</dc:identifier>' + 
    '       <meta property="dcterms:modified">' + formattedWithoutMilliseconds + '</meta>' + 
	'	    <dc:language>en</dc:language>' +
	'	</metadata>';

    opf += '<manifest>' +
	'	    <item id="toc" properties="nav" href="toc.xhtml" media-type="application/xhtml+xml" />' +
	'	    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml" />' +
	'	    <item id="template_css" href="CSS/template.css" media-type="text/css" />';

    for(let i=1;i<htmlChapters.length + 1;i++){
         opf += '<item id="chapter_' + i + '" href="chapter_' + i + '.xhtml" media-type="application/xhtml+xml" />';
    }

    opf += '</manifest>' +
	'	<spine toc="ncx">' +
	'		<itemref idref="toc" />';

    for(let i=1;i<htmlChapters.length + 1;i++){
        opf += '<itemref idref="chapter_' + i + '" />';
    }

    opf += '</spine>' +
	'</package>';

 return opf;  
}

function getTocNcx(title, htmlChapters, uuid){
    var ncx = '<?xml version="1.0" encoding="UTF-8" ?>' +
	'<ncx version="2005-1" xml:lang="en" xmlns="http://www.daisy.org/z3986/2005/ncx/">' +
	'<head>' +
	'    <meta name="dtb:uid" content="' + uuid + '"/>' +
	'    <meta name="dtb:depth" content="1"/>' +
	'    <meta name="dtb:totalPageCount" content="0"/>' +
	'    <meta name="dtb:maxPageNumber" content="0"/>' +
	'</head>' +
	'<docTitle>' +
	'    <text>' + escapeXmlText(title) + '</text>' +
	'</docTitle>' +
	'<navMap>';

    for(let i=1;i<htmlChapters.length + 1;i++){
        ncx += '<navPoint id="chapter_' + i + '" playOrder="' + i + '">' +
	'		<navLabel><text>' + escapeXmlText(htmlChapters[i - 1].title) + '</text></navLabel>' +
	'		<content src="chapter_' + i + '.xhtml" />' +
	'	</navPoint>';
    }

    ncx += '</navMap>' +
        '</ncx>';

    return ncx;
}

function getTocXhtml(htmlChapters){
    var xhtml = '<?xml version="1.0" encoding="utf-8"?>' +
	'<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">' +
	'<head>' +
	'<title>toc.xhtml</title>' +
	'<link href="CSS/template.css" rel="stylesheet" type="text/css" />' +
	'</head>' +
	'<body>' +
	'    <nav id="toc" epub:type="toc">' +
	'        <h1 class="frontmatter">Table of Contents</h1>' +
	'        <ol class="contents">';

    for(let i=1;i<htmlChapters.length + 1;i++){
        xhtml += '<li><a href="chapter_' + i + '.xhtml">' + escapeXmlText(htmlChapters[i - 1].title) + '</a></li>'
    }

    xhtml += '</ol>' +
	'    </nav>' +
	'</body>' +
	'</html>';

    return xhtml;
}

function getChapterXhtmlPages(htmlChapters){
    var pages = [];

    htmlChapters.forEach(function(chap, i){
        pages.push('<?xml version="1.0" encoding="utf-8"?>' +
        '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">' +
        '<head>' +
        '<title>chapter_' + (i + 1) + '.xhtml</title>' +
        '<link href="CSS/template.css" rel="stylesheet" type="text/css" />' +
        '</head>' +
        '<body>' +
        escapeBareAngleBrackets(escapeBareAmpersands(chap.html)) +
        '</body>' +
        '</html> ')
    });

    return pages;
}

function getTitlePageBody(title, author){
    return '<h1 class="center title">' + escapeXmlText(title) + '</h1>' +
        '<h2 class="center">by ' + escapeXmlText(author) + '</h2>';
}

function getCss(){
    return ".contents { list-style-type: none; } " + 
        ".title { margin-top: 33% }" + 
      "      h1 {" +
      "        white-space: pre-wrap;" +
      "      }" +
      "    p {" +
      "      white-space: pre-wrap;" +
      "      margin-top: 0px;" +
      "      margin-bottom: 0px;" +
      "    }" +
      "    .center {" +
      "      text-align: center;" +
      "    }" +
      "    .right {" +
      "      text-align: right;" +
      "    }" +
      "    .justified {" +
      "      text-align: justify;" +
      "    } " +
      "    blockquote {" +
      "      white-space: pre-wrap;" +
      "    }" +
      "    .footnote {" +
      "      text-indent: 1em;" +
      "    }" +
      "    .footnote p:nth-child(1n+2) {" +
      "      text-indent: 2em;" +
      "    }" +
      "    sup {" +
      "      margin-right: 0.25em;" +
      "    }";
}

module.exports = {
    htmlChaptersToEpub
}